
    description: Entity representing a <<resourcePathName|!singularize>>
    is: [secured, language]

    get:
      description: |
        Retrieve <<resourcePathName|!singularize>> item with given {<<resourcePathName|!singularize>>Id}
      responses:
        200:
          description: "Returns item with a given ID"
          body:
            application/json:
              example: <<exampleItem>>
              schema: <<schema>>
        400:
          description: "Bad request"
          body:
            text/plain:
              example: |
                "unable to process <<resourcePathName|!singularize>> -- constraint violation"
        404:
          description: "Item with a given ID not found"
          body:
            text/plain:
              example: |
                "<<resourcePathName|!singularize>> not found"
        500:
          description: "Internal server error, e.g. due to misconfiguration"
          body:
            text/plain:
              example: "internal server error, contact administrator"
    delete:
      description: |
        Delete <<resourcePathName|!singularize>> item with given {<<resourcePathName|!singularize>>Id}
      responses:
        204:
         description: "Item deleted successfully"
        400:
          description: "Bad request"
          body:
            text/plain:
              example: |
                "unable to process <<resourcePathName|!singularize>> -- constraint violation"
        404:
          description: "Item with a given ID not found"
          body:
            text/plain:
              example: |
                "<<resourcePathName|!singularize>> not found"
        500:
          description: "Internal server error, e.g. due to misconfiguration"
          body:
            text/plain:
              example: "Internal server error, contact administrator"

