      queryParameters:
        schedule:
          description: |
            Schedule email to be sent daily, weekly, monthly, quarterly, once
          type: string
          enum: [once, daily, weekly, monthly, quarterly]
          required: false
          default: once
          example: schedule=daily
