      queryParameters:
        facets:
          description: facets to return in the collection result set, can be suffixed by a count of facet values to return, for example, patronGroup:10
            default to top 5 facet values
          type: string[]
          required: false

