      queryParameters:
        include:
          description: |
            indicates which referenced fields should be populated (de-referenced) by the service
          type: string
          repeat: true
          required: false
