#%RAML 1.0 Trait
      queryParameters:
        offset:
          description: Skip over a number of elements by specifying an offset value for the query
          type: integer
          required: false
          example: 0
          default: 0
          minimum: 0
          maximum: 2147483647
        limit:
          description: Limit the number of elements returned in the response
          type: integer
          required: false
          example: 10
          default: 10
          minimum: 0
          maximum: 2147483647
        totalRecords:
          description: How to calculate the totalRecords property. "exact" for the correct number, "estimated" for an estimation, "auto" to automatically select "exact" or "estimated", "none" for suppressing the totalRecords property. For details see https://github.com/folio-org/raml-module-builder#estimated-totalrecords
          type: string
          pattern: "exact|estimated|none|auto"
          required: false
          example: none
          default: auto

