      queryParameters:
        op:
          description: |
            Type of operation:
          enum: [pay, waive, dispute]
          required: true
          default: pay
          example: waive
        amount:
          description: |
            Amount to pay against all current fines on patron
          type: string
          required: true
          example: 10
        payment_method:
          description: |
            Payment method used to make payment, e.g. cash
          type: string
          required: true
          default: cash
        comment:
          description: |
            Short comment
          type: string
          required: false
