      queryParameters:
        query:
          description: |
            A query expressed as a CQL string: see zing.z3950.org/cql/intro.html
          example: |
            (username="ab*" or personal.firstName="ab*" or personal.lastName="ab*") and active="true" sortby personal.lastName personal.firstName barcode
          required: false
