      queryParameters:
        query:
          description: |
            A query expressed as a CQL string
            (see [dev.folio.org/doc/glossary#cql](http://dev.folio.org/doc/glossary#cql))
            using valid searchable fields.
            The first example below shows the general form of a full CQL query,
            but those fields might not be relevant in this context.

            <<description>>
          example: |
            (username="ab*" or personal.firstName="ab*" or personal.lastName="ab*") and active="true" sortby personal.lastName personal.firstName barcode

            <<example>>
          required: false
