#%RAML 1.0

title: JSON Schema API
version: v1
baseUri: http://localhost:8081/{version}

documentation:
  - title: JSON Schema API
    content: This documents the API calls that can be made to get JSON Schemas of a module defined by X-Okapi-Module-Id header

types:
  errors: !include ../schemas/errors.schema

/_/api/jsonSchema:
  get:
    description: Get list of JSON schema names for the given module defined by header X-Okapi-Module-Id
    responses:
      200:
        description: "List of JSON Schema names"
        body:
          application/json:
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error, contact administrator"
  /{name}:
    get:
      description: Get JSON Schema by name
      responses:
        200:
          description: "Individual schema"
          body:
            application/json:
        404:
          description: "JSON Schema with a given name not found"
          body:
            text/plain:
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error, contact administrator"