#%RAML 1.0

title: RAML API
version: v1
baseUri: http://localhost:8081/{version}

documentation:
  - title: RAML API
    content: This documents the API calls that can be made to get RAML of a module defined by X-Okapi-Module-Id header

types:
  errors: !include ../schemas/errors.schema

/_/raml:
  get:
    description: Get list of RAML names for the given module defined by header X-Okapi-Module-Id
    responses:
      200:
        description: "List of RAML names"
        body:
          application/json:
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error, contact administrator"
  /{name}:
    get:
      description: Get RAML as JSON by name
      responses:
        200:
          description: "Individual RAML as JSON"
          body:
            application/json:
            text/plain:
        404:
          description: "RAML with a given name not found"
          body:
            text/plain:
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error, contact administrator"