#%RAML 1.0

title: Tenant API
baseUri: http://localhost:8081/{version}
version: v2

traits:
  validate: !include ../traits/validation.raml
  internal: !include ../traits/internal-error.raml
types:
  tenantAttributes: !include ../schemas/moduleInfo.schema
  errors: !include ../schemas/errors.schema

/_/tenant:
  post:
    description: Initiate tenant operation (create, upgrade, delete)
    is: [validate,internal]
    body:
      application/json:
        type: tenantAttributes
        example:
          strict: false
          value: !include ../examples/moduleInfo.sample
    responses:
      201:
        description: "tenant enabled successfully for the module ID"
        body:
          application/json:
        headers:
          Location:
            description: URI of the operation
      400:
        description: "Bad user request"
        body:
          text/plain:
  /{operation_id}:
    get:
      description: Get operation status
      is: [internal]
      responses:
        200:
          description: Operation returned OK
          body:
            application/json:
        400:
          description: User error
          body:
            application/json:
        404:
          description: Not found
          body:
            text/plain:
    delete:
      description: Delete operation
      is: [internal]
      responses:
        204:
          description: Deleted ok
        400:
          description: User error
          body:
            text/plain:
        404:
          description: Not found
          body:
            text/plain:
