#%RAML 0.8
title: Address Types
version: v1.0.1
baseUri: http://github.com/org/folio/mod-users

documentation:
  - title: mod-users Address Types API
    content: This documents the API calls that can be made to query and manage user address types of the system

schemas:
  - addresstype.json: !include ../../schemas/mod-users/addresstype.json
  - addresstypeCollection: !include ../../schemas/mod-users/addresstypeCollection.json
  - errors: !include ../../schemas/errors.schema
  - error.schema: !include ../../schemas/error.schema
  - parameters.schema: !include ../../schemas/parameters.schema

traits:
  - secured: !include ../../traits/auth.raml
  - pageable: !include ../../traits/pageable.raml
  - searchable: !include ../../traits/searchable.raml
  - language: !include ../../traits/language.raml
  - validate: !include ../../traits/validation.raml

resourceTypes:
  - collection: !include ../../rtypes/collection.raml
  - collection-item: !include ../../rtypes/item-collection.raml

/addresstypes:
  type:
    collection:
      exampleCollection: !include ../../examples/mod-users/addresstypeCollection.sample
      exampleItem: !include ../../examples/mod-users/addresstype.sample
      schemaCollection: addresstypeCollection
      schemaItem: addresstype.json
  get:
    is: [
      searchable: {description: "", example: "addressType=primary"},
      pageable
    ]
    description: Return a list of address types
  post:
    is: [validate]
    description: Create an address type
  /{addresstypeId}:
    type:
      collection-item:
        exampleItem: !include ../../examples/mod-users/addresstype.sample
        schema: addresstype.json
