#%RAML 0.8
title: Proxies For
version: v0.1
baseUri: http://github.com/org/folio/mod-users

documentation:
  - title: mod-users Proxy For API
    content: This documents the API calls that can be made to query and manage proxy relationships for users

schemas:
  - proxyfor.json: !include ../../schemas/mod-users/proxyfor.json
  - proxyforCollection: !include ../../schemas/mod-users/proxyforCollection.json
  - errors: !include ../../schemas/errors.schema
  - error.schema: !include ../../schemas/error.schema
  - parameters.schema: !include ../../schemas/parameters.schema
  - ../metadata.schema: !include ../../schemas/metadata.schema

traits:
  - secured: !include ../../traits/auth.raml
  - pageable: !include ../../traits/pageable.raml
  - searchable: !include ../../traits/searchable.raml
  - language: !include ../../traits/language.raml
  - validate: !include ../../traits/validation.raml

resourceTypes:
  - collection: !include ../../rtypes/collection.raml
  - collection-item: !include ../../rtypes/item-collection.raml

/proxiesfor:
  type:
    collection:
      exampleCollection: !include ../../examples/mod-users/proxyforCollection.sample
      exampleItem: !include ../../examples/mod-users/proxyfor.sample
      schemaCollection: proxyforCollection
      schemaItem: proxyfor.json
  get:
    is : [
      searchable: {description: "with valid searchable fields", example: "name=aaa"},
      pageable
    ]
    description: Return a list of all proxy relationships
  post:
    is: [validate]
    description: Create a proxyFor relationship
  /{id}:
    type:
      collection-item:
        exampleItem: !include ../../examples/mod-users/proxyfor.sample
        schema: proxyfor.json



