#%RAML 0.8
title: Users
version: v1
baseUri: http://github.com/org/folio/mod-users

documentation:
  - title: mod-users API
    content: This documents the API calls that can be made to query and manage users of the system

schemas:
  - userdata.json: !include ../../schemas/mod-users/userdata.json
  - userdataCollection: !include ../../schemas/mod-users/userdataCollection.json
  - errors: !include ../../schemas/errors.schema
  - error.schema: !include ../../schemas/error.schema
  - parameters.schema: !include ../../schemas/parameters.schema

traits:
  - secured: !include ../../traits/auth.raml
  - orderable: !include ../../traits/orderable.raml
  - pageable: !include ../../traits/pageable.raml
  - searchable: !include ../../traits/searchable.raml
  - language: !include ../../traits/language.raml
  - validate: !include ../../traits/validation.raml

resourceTypes:
  - collection: !include ../../rtypes/collection.raml
  - collection-item: !include ../../rtypes/item-collection.raml
  - get-only: !include ../../rtypes/get-only.raml
  - post-empty-body: !include ../../rtypes/post-empty-body.raml

/users:
  type:
    collection:
      exampleCollection: !include ../../examples/mod-users/user_collection.sample
      exampleItem: !include ../../examples/mod-users/user.sample
      schemaCollection: userdataCollection
      schemaItem: userdata.json
  get:
    is: [
      searchable: {description: "", example: "active=true sortBy username"},
      orderable: {fieldsList: "field A, field B"},
      pageable
    ]
    description: Return a list of users
  post:
    is: [validate]
    description: Create a user
  /{userId}:
    type:
      collection-item:
        exampleItem: !include ../../examples/mod-users/user.sample
        schema: userdata.json
    get:
      description: Get a single user
